apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
- pairs:
    app.kubernetes.io/managed-by: argocd
    app.kubernetes.io/part-of: fawkes-platform
namespace: fawkes
resources:
- cloudnativepg-operator-application.yaml
- db-focalboard-cluster.yaml
- db-sonarqube-cluster.yaml
- db-backstage-cluster.yaml
- db-harbor-cluster.yaml
- db-datahub-cluster.yaml
- db-plausible-cluster.yaml
- db-penpot-cluster.yaml
- db-vsm-cluster.yaml
- db-unleash-cluster.yaml
- db-experiment-cluster.yaml
- db-discovery-cluster.yaml
- secrets/db-focalboard-credentials-sealed.yaml
- secrets/db-focalboard-readonly-credentials-sealed.yaml
- secrets/db-backstage-credentials-sealed.yaml
- secrets/db-backstage-readonly-credentials-sealed.yaml
- secrets/db-harbor-credentials-sealed.yaml
- secrets/db-datahub-credentials-sealed.yaml
- secrets/db-plausible-credentials-sealed.yaml
- secrets/penpot-db-credentials-sealed.yaml
- secrets/db-sonarqube-credentials-sealed.yaml
- secrets/db-sonarqube-readonly-credentials-sealed.yaml
- secrets/db-vsm-credentials-sealed.yaml
- secrets/db-unleash-credentials-sealed.yaml
- secrets/db-experiment-credentials-sealed.yaml
- secrets/db-discovery-credentials-sealed.yaml
