source 'https://supermarket.chef.io'

cookbook 'git', '~> 9.0.1'
cookbook 'java', '~> 2.2.0'
cookbook 'nodejs', '~> 5.0.0'
cookbook 'docker', '~> 4.6.0'
cookbook 'maven', '~> 5.2.0'


cookbook 'vscode', '~> 0.1.1'

cookbook 'aws', '~> 7.5.0'
cookbook 'chefdk', '~> 1.4.0'
cookbook 'vagrant', '~> 0.9.1'
cookbook 'virtualbox-install', '~> 2.0.0'

cookbook 'chromedriver', '~> 2.0.0'
cookbook 'chrome', '~> 4.0.2'

cookbook 'ruby_rbenv', '~> 2.0.9'
