source 'https://supermarket.chef.io'

cookbook 'aws', '~> 8.0.4'
cookbook 'git', '~> 9.0.1'
cookbook 'terraform', '~> 2.1.1'

cookbook 'vagrant', '~> 0.9.1'

# cookbook 'main', path: './site-cookbooks/main'