apiVersion: kustomize.config.k8s.io/v1beta1
commonLabels:
  app.kubernetes.io/component: surveys
  app.kubernetes.io/name: devex-survey-automation
  app.kubernetes.io/part-of: fawkes-platform
kind: Kustomization
namespace: fawkes
resources:
- serviceaccount.yaml
- database.yaml
- deployment.yaml
- service.yaml
- servicemonitor.yaml
- cronjob-pulse-weekly.yaml
- cronjob-pulse-reminders.yaml
- cronjob-quarterly.yaml
- secrets/db-devex-credentials-sealed.yaml
