apiVersion: kustomize.config.k8s.io/v1beta1
commonLabels:
  app.kubernetes.io/managed-by: argocd
  app.kubernetes.io/name: plausible
  app.kubernetes.io/part-of: fawkes-platform
kind: Kustomization
namespace: fawkes
resources:
- deployment.yaml
- secrets/plausible-secret-sealed.yaml
