---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: db-backstage-credentials
  namespace: fawkes
spec:
  encryptedData:
    password: AgCFaFDalCrO0m9sh7gyS/5ZdkjXoKT4Cdw3+8OvTgyP/5gJ+JYQXCIxNfj0spbJ83ijTVW4KZLOLsoC1ZFD9EEUcWWz7WKumHmbMy7QiUJKlwSv0Ef7NDEp9+4UlHPEpOHapE98pGRjqhRkGCccSf4dbuaYd+PN9S7eFg4H+3bJuTLEazmiyHPWQhkOn1rYdBReNF60M68g5vNy0olFPwJvOH9uO13qZnXRWVCWspz0Ow4gcPlyQT3JNolF3KiMKt+q9P2cZZtdU7jwMIxmyYKNIL3So8/DLDlOrbWq2N85HZA9i5sOkkQ6ay+dPiyoNv3oBfNRH0gWH+J6khPrTIK7tADEUjSYSsJ3jxMUupoQnELlUrRhIQQNJQuKzwWn3EoL6w10WyVKig7Jd9koidTBQMtMecNa1fsdhuHWh+wQhjnVxGJu6GsgJbeHVF/0CdJhPNxqp66xcA3hVn0rkoq4OKvTzhxZv8TfqF+5iy2O3gUJ+n7JRO/p9VOiUSD7TcwLbTnauDvxJPEwUIVn4cosJInxyDoty4BMgcZChNnGmMwDYR68Gu9XuldkxTCea8pow9y5f8I1e1M3sBhbORG/LwHw9Qo5eEtdM4W1L5xlqo6uDWh2yUy0kMI7YuGy3auyankrVpS5QsIJAabFqWksJWC5LE+JXbchH7geAVJ5e4owXCzM2HDXZTJZ8iEnCwOLUS/4A3lFLa3jvliAr2O3mzP6XE5GOk4U2hyx
    username: AgAhwZhgfAjVPZB0LsxVSC5hZ7WtfQsvd+UPIOkyuh39suPPjdjYC4Yp6FRqpRM1+ZqLMM1faoKiyaJmicqoNHzIYsczYnNLlUyrGmswGCTOMARJWT+QizRULd8XK2nX+ldWnZz7vEzwX7b/Bl1Y6ejgHvyKZnoD83wO/qhmgRuzsCicI0csKnXDPOLcZIfJcf03zMDlEaAYHlnx3vpA5i32dfCGU9Jp6CaqkXL8LjcBK7Hn9VsgBXUcvgnJyKweFbxPyOJqxzSUyveuxnUyhvH5pGWSK8MwvGDo7XyIV9ZiEejWWuaGmHFTshMa/pB4vEBA6p80bXLQrNVJNVVoUEQ2jUC22Dy6DAEtkeG0vdeo5NsA0C5M2gLY6EPfO8W8gVAoK9KmtNxf3QbmBLuiZ/mWcA1XGD8/3juo7tY5JwI4pZ0MUqeMXjNyiwfXPwRzvG6eExITW37HUfQndP6EAi+4NrjIch2aCZYxx56yZLibBjOnaodrAblTbe89RdDfOrpXPAHOVgrcvWdqi+RGUUoVLqUsU1aZ8wOhxl3Yi/uD5ms+/wIp+aYXVRbXOhAZarroS5fyt0f28tXzJJTxDGe6R8huzPrEX0nnYhGuCis5BhW7C2mWimXDGQAArNoN2UGK9+wZFT17wOWS8O+NeFIbLCZLXPcAvTqtm3pgLjN76TF3S5SGrIOrIvKnhxPKZ5Lwd4ISDJJEPHVUq0zIiw==
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: backstage
        component: database
        environment: dev
        team: platform
      name: db-backstage-credentials
      namespace: fawkes
    type: Opaque
