---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: db-backstage-readonly-credentials
  namespace: fawkes
spec:
  encryptedData:
    password: AgBJzmGDnX+cFt60+Zu943dgKHeXstsP3MIdHrHjm7t/yM7pwJ+HRw/xJ43P+oLzYTf5NF03HvobKCPQTfRx+QXlQTnPrCz9ibOpfAt4cI/7ADCimXo/+B7EbSreIu2x/FUI4Ta9ifPRn0ypa7/fdgHwZB++uHKRfeuwe/ZYeg2FqrGXbQ5p8shJT96Z/VoAJKFE94XZmbCrSnsbe0iHo+l8cNkQ9zVdP5zL0SsPkFBwZu0gOMHREo5Ih6GBbTVH/zHkdS5MF2t8okC61PvoJMON7qyJVW3g5Z4OSBFPBdpoo5YpzFGn5IJVy5VT5MLhMsAMRUQlBT07bEO1mc8YCftPIyybvCrw2V7aJgWBzZOPXXTd3+hIaOhukuNFuzQu5MxRv3HmmeRgGPDbfhtbU8e3P9H41E86Y7gVflwwkzs9hKyGVAIkwnIBSNg3cgBbbnk+TbqC+Q1QsBtnJjXvjQvVnl3cl8G495rWT0VSRzDbsTP/0Ibdcb+7boX5ztFhucRK3cUty1bzYOK36jeahFiHHqx4ki0SLYYfMxKkAPm0DWs6zqIFO6s4YsfE+fYZ7wSsSf1WbLN46F7h1gcqmz6sioMPWQ1xVrylcHzA05Z8AqGrnMKrLlq00OhpfASiTyWaq521tpum8sDIAkcSDo+LDgAnP3FrxoVFofNb2BZAhTsM/wUNS/G+ood1QCscDrjF+HgPAIIVDlwQyMjqiP6K2zlN2KCdwGqBfawslP845Cupf+KM
    username: AgAMA1MyEOCKjzE6nYp9dd/MQd3SDQ4Cy96+K+La3Qh0VreGqqOjoYXVWnb6QaOosxi9yFgc+okPcHOsNNvVdGl5U0Yjm700DCDZvpHMOcmSuWB4ymXBZsz/ZaJC/GfhqpjWuPEmBEsmLDUiGYnYMsQifIYZAYGRG1ax5Z7LEhlp6YaIKr5in5HSdG5jQ4EWfzcbkag44u8EUlPbQ+SpusI9dhzXKCs+6tZAZ349S5tDS97DtEvR6OBzq470LI7PMujRYZBA/MSIuqUQD6jMzKpXP3ExON8zqkZXnYexYPJmAhYs6zAhEtxpbEB+QRmXQIAHb3aGML3h2lAvZZoUZnpgJLnGyCUgJ5iI0PgXz0/dEpuBQBbGnsGBJkNlGEZfaKnfGc1XkA3w1Jh8+FWb9bv7W5lhKqKbqu+GIElfaMDbvDz8pRQmEpQEdf1Zcrnl8aCVwSW1YnFr+ZXYfNsRhfjDM48XVNjWYnpBktX9Bd6b/Vw0AkIDZxwG3GizhunDISaxGmUfCQXgs/1EYhL/llNxSGHLUp+zBUIvLa6wgmMaGwzRQWJDF2SQXGaxtpPyxPnjPlcZwT972JMJGqUj201EKn/sE4RchhHe7QS42DGXcFuLvmzGMMFL9q+j0QWH+HD3zYnk8jNwbl35kXobNpDGczJDV2HcdR8n4bf5XyEZSZprR0ZRb+YEBuAj3LE4+NS7pPodtMGVKeBWIpTTmewoqK0=
  template:
    metadata:
      creationTimestamp: null
      labels:
        access: readonly
        app: backstage
        component: database
        environment: dev
        team: platform
      name: db-backstage-readonly-credentials
      namespace: fawkes
    type: Opaque
