---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: db-focalboard-readonly-credentials
  namespace: fawkes
spec:
  encryptedData:
    password: AgBzOGVc6fa5gt9koo9PXvF/gT04pWnfeFo71Axt5wCiito5hS+HwlH+8IfNEGKoUq82qS5BqUpuA188RunK5RVp6YaOxeWNU1o7MW9Dbi2Coq306sNYYc613EzIj0YhkRP1VhxXe3GWu7Z1HjeU54glNlQCyUWRvuYIQ3qiOgwzry4OM2KkwL+tsqXDFzoNbbtth7gGblZuevYG5HrBB7JHtYSEzJHrGzi3h8h8CUX4wzMkRcUSV32HCwp67ciaAjEAJ/CHvnIM5LL8fJbR3Ool+qRPcot68K136jjgZLjFbqxPpFDn6NgeLsRs8WAMCK+zCP+3OM/FMrOQOeeYf6Zh4avbBn1Dh8QclnFKvN2mk39vsHWrYmW9WyJz5IMZ5gqfTHbTJMOngvsg608qTFE6Bf68DmCBjTn3synFLXGCKlH+bvoBSsD0Fgmrq2uaG1OREa4caWZu+/jder9ttNh06vU/AkcZRVgpiE0KxqIVXUU4/DugNHHskOs2MIdNRBqaj/ZnIC68KlJXPytoocbuK+YZUTDc/cxRE1/SWbWcNkdgd0o9DM2dSOhZLSJQsZvbzo5UFUB7rreYm7fdYdhtV426pBGJ9zVh3LgShnK/9g1/HE9301OTmS55icoH1GzRyrmLuoUJcgs2QBUHzwpJdORIx34Emha6s8xX7jf5gQrtpaP7uY/EcZ419ttWPKQ1rBv2uqX/O7dDU5RFU4UH4mmL/2eJ8Gpx/OyLrS/aqLwGipn8PA==
    username: AgAT4BPWW4Mkai96fTGvQjRXSrKVRwUc3l5eFbXaq8COkztY7VGZZJDY+CR6ydK172Nhx8etL81nohdKUJdSCkhKyyHAVC9NZmmoYJMI9M2T4VJYPGIsqnQu9oMKtVM19tNz9Bl6ON9t9Dzm9Co0WXKkhzDd2wuV8K0T019kI4pmBtwSSsazZdMYcNMBDHFaLH4NCR5vQhZqscqBkYvcS2zOPL0EhctCHqcC4y+eU6Ka3z+jGqfZz9Ax39cIyqEAXGbd3S1n9M8KXttsG1ReXEfCP1h9rLjzswcPiCgUQjLXN+Q4rKIXMlYUM1JkQyELeT1qJBgaziFWa5fJ2uM0q+HKZU5gC7FKnPzT33tmdmIRymVej1dtDOYC0xmgef1CqcZQZq2wgLx37DCCq8Ao4uAGk7PJONplCpz9+mT1BHTLg9oj+Ynr9MduFAjl+fei3LRgnZ3B7FTJa/Qe7Uy+4OEULZbiMW9SrOJ69iPJMHelqrmO4bMNwpthHUXMUhQ6YdOXfmsjtpYHePGbTajknBiypImSyNiUG5mWSc/PUz8Wd9Gxyt+ayqLVxbyKmqbpjkEscCILjaVhaNcBuSuQv8JwmL54+MZY7ulCEBfZQyK+KACRhbBw3lTxM88fjuy6JgaUNrKcPPGFOfhy9ZAL21SfXs9P2sZpccrvyKHE9CeM5wicuPE5u8GjE+ysq9cXFVF8SB5KRTJ5+qayYy0EOtn7qJzB
  template:
    metadata:
      creationTimestamp: null
      labels:
        access: readonly
        app: focalboard
        component: database
        environment: dev
        team: platform
      name: db-focalboard-readonly-credentials
      namespace: fawkes
    type: Opaque
