---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: db-focalboard-credentials
  namespace: fawkes
spec:
  encryptedData:
    password: AgAuO26mbrlkx9sXaeGrQ2rhw+m+EP40qNmR5MW9fOlKccIdt416kUf8hAHH3Y6DFb4JNa4HX33mlwi5qwf2soo/Uh+1GI6DR6s5ATieNxRLh869HKBohOiENqD51ouBQEU4HrmU/KvsBqW+a0qbw9ENnh3Y8RarYLXekoKOON/5eRXce3Urn3xwNa877la7x5pYdcb5vnTjIOuY3MwgecrHf+nJ6/RMBJJfCz7EFc3yTVBmXZ0mKnujh9PDc/O9UkIW0KW3sfapYc7Y71iO+1pct9wn3xn3jAbY3bq+0nMmUJlv9rWoLfqzbE6HdmwP5G2Nf5nUjkdTCjoux93AY33WE+FlKMd5VwVeTb8Kw+gzF9googf/ZefrIuRDgOCjsaiau88xLnxWCVTQX3eI6nYRvquEkS6sQdU/ZHSDTmh1waj7MbE98H/CjXucxrl99Vi0gTEIn2riQvhiIRf4sFwekIYDcHjT/2G6qEcDP3LOhjrlmV9PVj2sXFc7daz8I7rYAFguNmSl9+hNZnv4cjWCHZnHxMu+NDVHqXdT9kvvTNPXSKbTHFbHaticcLTClO3hPf/T8kcMi6Rj70xt2RiigSkY0ayqi6Ea2GCwfgNMoluFMC7PvRZR3cj8qQQNzmwnf5tigREei5kd3kN/rH/G9HzMtSDGijukTNo8IIrAYJAXcxeQ1fvIKdMaCJDBrV7Zj6nkQ/uFMh8hy0Yj9gaEfV7PUssKeODGD21nTg==
    username: AgBst8opHraEqqIXIBRWKItKJG2G8TCGPRWklBu0ikgLk5Lu0aWu7duilhdN3PVE3/Aa45xPt6hTM442qkx0ObsOaLZ5A4X5mkoGttegEKcIekIAFmgb/0X20LOlKVuTGq5aSakvFqwaOZHImqJiYzXdI5EFF54oZgFliKBJSlkEvl3gqqGd4LYyOvTOQCAtJ2FnvFgdBMMoD1vIckZ1HH9h8VMVnNLh/xRKdt2dBxvtrTgCvg2+9kV5Ltc/k03rMKcfTVcK79ElqQzMxEQFrrlphbQbhwISoS1ds766CLn6RzA+aAWxaNBUD10NRZgUVzX/TkDAkoHcqacE4Ryd/G+IsGPJU9JnTd91FUnb6K1hP/VbwFjVtiFLUmWoOTHn3I/5RCZX2dprxHFaVJDKOCDadErA0vwy/5BacoU7c8EyonbRqNgmyFy2ono6jx+ff1vlzQZsOMNtSCOPleZb4M9+loKqThD3YzH/nsTschagD+fG7p3evnAjsmuEhOVXczPQDnsB01jtODN+w06a1Hh3B+ilaCfCG4iF35tZhAdV9wo1lOvHQotzIvz1h0GN7ZWFQjaqmkLY7a3lJ38JvVOoOumt8cbzR2IFUNra6ECgQAgYNimcKFEOnaTIa5ogSgQmOHp+Ko0NGuIpFT+2WgnAquBwpsh+4vy8veg/WPDPokojqPofgIOnER/Srwl/sJX1YR3F8joluLiy66ZAhHQ=
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: focalboard
        component: database
        environment: dev
        team: platform
      name: db-focalboard-credentials
      namespace: fawkes
    type: Opaque
