---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: db-harbor-credentials
  namespace: fawkes
spec:
  encryptedData:
    dbname: AgC6u/g4n5zGpc51cEH46H+89j4xIENVctNyvyiu5VTXNBjTQHn8Ydjqnan0odmR9FYAOETEcFEvwJEJ5E2xM4LqhLcwWj5bcG3m42gtGGXFtLyvkW9+NgwENRKKLNHI32Zda7Xn59+Dnx5JfJAytzgW03Oekm3FchWzNpSQ/gmuCXeoVFMVLCspe9EKovLbufG+lr0AItWUhF6f3i7ihu/lMx0CTaFE6WDDPgDhD7LgVYUn42a0yuSIC6Q/8MUlqtk5vHYa0zQwI60JN9Y4RYPhTxYMcsQPIcPon5tKPLweE38UhTtBLvsrSeRN2H7tZbWN1+W5MdK1GscLwMpJZk6VoKb6g1M7Qn1VAXikZD95v/xtbjmkwF3ejPT44r2MhhsNUwwLoGWLHi92tOjbVpZT9kPssxnZ0WQsiwZB4cIEK72msVmuxK0JQmX/q7M62QIN9euZB5UvXXkornIgMI4N0XGvP2TrWZ3P3VRc8977JY3KxwEWXPR/yKaFRoxnoIbu2dQ7ZEJTlZCYyHQntdhUM4UV598YoLPm2VAFtVd0YlUOrcjNL/Nf0gtnAhSqOaa3MtWXyqlIGjsLBk0I/IFk6XopioFtkC7QMx32wVfYye2pVcMipt3vuGjVtettXpf1FKz3xqg10wc8Lj4jbNLTipISSDmzXT8oYojFK1wwPZg/V9FcnUWCx8c+c1xZ+ngvTZURLSo=
    password: AgCMBAhyCeTsLse5TPs/m7OvvV/SpPDkUqLqDjedYiFGJS5wRV08wdKUaCcu4waQTf8JL0S5FDcNsXtzwT/tahHsg3mUK+WVCCPgc2ry+hay95Zu8LrvYW2dOrqSAtvizPx+4RA+7eAMiiSYFqyoKgnZ/Lq3z+Rzdosds2q47skZdJwtZsNqsnxNSBQHXpXiY7uTPFGcGH7W4q43w6ZcVHUa3iNh1gVwX+M00j0JBeBrmuf0szUO98z8WH8FH6SirRc0N6ocvJr/VRU9w8C7omql6Fb+NhtOdxUXIyv6h6dtiI3+cC+GqN+dwByuwoZ/beYWECoFQHlWIi1F0UAQve8taIO0uWPrY56p3C5Eetww1U84R2IpIN/V/Sy6AgxzRBUykj1b9sGe40+3rw4tKEm1AYVZ3xvvSv39ZMXAU7ppvl48o5n/jPGD6aQqXNDoe86FKcnZUsgxaTBR7FN/Lc8yCz+owJoAhM51m3rmXdS/rdXRsoHyenoCl3CN7wKtvtktD/Q7koFxS67uJvvevx/W8RCPwNx2+tHGeTE+FL10z1XsZQ2p4/Zmm8qJxcNazoUa3dtgXVQcX/9g9poadx9wVKHfoOSu2vg71LGUtvbdc9A08gEX7e6nZwqUWnxSgAo5fc5vXBK7xgNluxYp9LVltSchMVcuaz3+eRq6Iw9yHsePKZ8mgOcGjAPqtTtgaMYX1Gah14J60yREp43TX98TiqFDfhcI6E1d
    username: AgBKZw8zFkPmTEtQ6eFKfDX/Eo/z5PwirbG7m4AG07c9/iP/tXgbM9Sp5FBmotOX16GqCQeYZ02XU9ivqiFSDPryQhoAXDFGLlKPD2a3Hy8WC+1q2W9DdsnrKx/gdFuGhf5B3uGuN9nPe3CqCX6ZxqzcCdEBMZs6cZW8XT1XvS68QnRP7+UZNIB8nG4Gb+4CjDR1EpZwswtSkr4tXMEyzslt04EK6UrZNmEw1cVzG0Ym8VqYacyGpEeVwenMweZ6rHjSwr4UqrHXhvmpOnDDJ+I81YEr7bfsOi7HCldF93KHpaakHK68eaV8P6WndRUbBVPnfRY305FN68dzoTjHVZVc800bJA4v7h8RpoIc1ebAVHVG6NvOrIyXLmIDToN9rn9cYibfQDHePKjhIRksHHRfzEbsyYsJf0CBL6S327owthXSjGjJm9ww53gUNe5X51Ey/QnXgPc8Pjy9W0T6JF25NnLvQkL0Nge9MtbdlrGBI82RHAq0OyMZfRuF8gU/gVcZ6mf2AMatbtyl3S/KCRgZDXQJoO81UE1RUueyKxISUj46RPht1hAhkQFpShyL0Qj/SVrbHEbT/j7BLr5Q4XipVt8ie5OxCg9tBTndS7LOI9exRxufapfEMFQdAY92/mNUi0S2XxIeje8P6HbyRF1nwxAtqz29enMvna36t8kzn2DAlK+6YKvGm4VkIOsULVw5di1a0evyPYPkFg==
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: harbor
        component: database
        environment: dev
        team: platform
      name: db-harbor-credentials
      namespace: fawkes
    type: Opaque
