---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: db-plausible-credentials
  namespace: fawkes
spec:
  encryptedData:
    database: AgBstObOPfyP2F3/uEd9UiiB0kvOfFT+S4JZg1Cq6+nyemcFpptyLb04P14Ph2ByvNXd5mN4rUNcT1LKKEijK6MD3ZlW6AXpJtPQXKhTKJBVAOZA2UjcXuJMYxhwbta+45e7ucM1qjp77LcI3iQWmuXYCu/Ub0uYWff4ONC/1Q9GHlntsPVxpWGlovPkXxtAz5CVM4IjlzRh4bZ362JsgiPLYdepkfGHER58YZjmC3mGywNlObjcqbMJKWj0ycjI+fsAYAWsXd8s2EFh0amjYH1FkkMSItAk9KPP4jGg6BPbLc/Me/GpeT26x+64Zd3PT5WMG0UkowwE5QePJecTwsNi7ePrcharB/WbTuQUv+jE5ZBOCiRqT3IJn649g2ioDLSTkjGJE8RQS9lhdnvwArMRDobQOVmq9SP6Bt+uzTfSVt83y7v0bfWFZjmlAq/2b8v5WnjhP8pywE9AYKV80/PLhznSk3NHZj9vH9TB+gI1fx1x4fkoUinGyJcL/hmkrE1ODr1+gCSvdCfgtJKvhyzBKvLdMukYQmJeAi/i/TQmYjogyFUk0Q5SFQggjzqI2K+ADiR2HujuBqu+wwiQdyvxd83bvop7spxmE52J2toDgpQrLwVd+tPpoFJUdNE8yTIUgzLR4NVTlCw6g5UuJT3SrbsYy64DDaO7ArJW0pxofC+4Zynlm7wxoV07/lYjE9SERbQr5Jwwydm/Z4A=
    password: AgDN4xqVEIIBLSslqgPGBJuiMbACHC5fwmkRwj4eklkRtgmstuPHK3uVlNuKdx+bu+OFXEe5vAFuPZXtig7IwyXPgH2q6zTWJEh8FjNScKgAAbz+Z7IN7sSBLmgRqj1+SdJhZj9UIeFjjljUDbHTYW5rTcQZyqs1ZSTvViPa2P2EeOhXaLO/NDY0oSzSflRcYvZHx+Vlp8MZoHsSfWL5vg012wvgIbPnBoARMzbvYAO2jGyBPyqHf4EkNmJGwhhJlVghZRl0/G/V7eq6hwhlrwc8OJVFY25DIa/Hgm+BhU1SHjHfsyLRCQiCZKNDdcDBa2g7w74RCXgRYujBjxjySUDbjsK0oKnT/nKWKQAjDMoQYcIMX1WaqJHAMXJFW55KE9duWlT+lKxYUHuKFJHQQgFpFPCm7MfgTtdY4w5Cjn5r5Koer39zK8kbnPwhQklSyaLgHfWQOBPJWcIj16Bx/D8GXXBm7io/XkAMU/PuI0ieD3/s7G9OG08k3E9j0YMhh6Juedyvkla59hfFdTaMy1NRpcB2/EdpDCiW44BzdHS9NJitTFHUctXg/cESLrN1QOTcAknGZ69neD9Lvh8RqSXyvnHXUXgGODL5+sq1VKZ0tO2tGLqknC14jW00A9tuNV9j4eyaOBgy+is8i9mD+hKGPutFXvxEVuJOBv9BDKVQbu0gRaaN1xroeXjYjsDVNWKpkvyCuP5q1Xtbqhn55l+m09JKQVf9QBuN5mC/6aY=
    username: AgCkyVipNRTakgat9CXWJ2oyqKIEnkrrPuNqmdLo9PMZ/1HIk+Q0pmE0XwKBrsnlWEUuwJ3umDgbTLLqJ4kGk/7db2pwR/OyteSqI6x4ujmMuayK0wFH60A17mQBmzncl4jxaQzfvi7xFLjdSa8K1ntiWKOzv3P3u51qGHJvymwXRHntaMVHCiE/JTbjMjdW29E4Oqd23buRii6ymbUddfSJzafqr+WK4Uzjmg99zkO1Du5+B2etnUFrgyjIVTmIjuR9/2nWolnLPcfKClQjRy6MQeBft7fRuQlUBX92GIGFvJFsSnQAwJDmmOQKDD5ggclrLhbRLRt0GtwLXk/sco94pH/qHCWMUTK762zrxp9JYrMKEtuBIgMcd7XTsAzoOz9aNMtdcNvPnI0waBHOulvoaHyK6kfyOOl4eNgqxajXQkBj9k8FZ7uPFkUptT7Zj67YjwwFQYKFgxL+8o/7xJmCN129EcfFa9okoPXXDQginsZdXtFwSnOTspl8q+rD0vKEzoCR1vfs1wwjUIix2JG/0P8uRTZnY11gh3Pu5JAeAsk8NSKi3GKV0q+NMRaVRXz+MRPYJmTvqa9N97M7AZT0tPfaF1Cf1BJ/3bMWi1yc8Dcbi3O/diNu8q/c5KI+X/Ylvuu4RBaw8mMZ4/m5ZL/suKc5CGKDzJZ2YHlzqjzv4Gxvv0gyG4s/AKH9b4VEKt83jya1FGKsMXupKuF3Aw==
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: plausible
        component: database
        environment: dev
        team: platform
      name: db-plausible-credentials
      namespace: fawkes
    type: Opaque
