---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: db-sonarqube-readonly-credentials
  namespace: fawkes
spec:
  encryptedData:
    password: AgCxc4ENOapPe/H2RWJ+gceNC1njpwiH6AuUQvOa8RlHpd2I4LpD9Gat5dgN3bjQesgehW+Ksz+GMlSVqRtJpYNKj3peeYbtQcTkpZzQmmTx3KZmDSwgNcSGVWp9ezAwXiL/oUBcKtcc7GJqtc7aMxInsyJ7Ix3A6fGJHFBw3V0oNi5SXSySq9kWJU3o9scBSJGeRg+4XGqfc60zeISegrUdn/pmutv5iiEYiZaqxmJLlXL4VQ8VAz2orl2okIyacCbnhBRAdcWkXiEdWbMMIAh7K4lUdH/V17yATepgp6bFQj0zSYj8+ikTpkzyIXeo9HPYVpFl5g2VpXTPQrjmfgY8spsOY1+NTczFkkng/S4drkAhq7SpGZNrMnQF6FiCZury5xQ2/OMOveNJ3aGGzULqB4fr9yA9piRHttTkuvct0Rfh7KEazuYQbEqPFhm1ig68dfabzL2wP9QHqMXK/QuM7ugcq5Ha0LfZXxeQt2m2JjAFVIJKDoOQ8Y2dZg+2TZn9NpaUoen4zs2hhcAkm00wI8NceMySK5dk1gJz9CmEBBbqMNTUzB1NEbVm8PuzIHimkqxrtcQjIlO+GLlgI+uAYfU8N3BmI7EIXTGlhbWpkpUHsrz7SHa029jW0nb0QauPoWaFMNkIw8LmA3Ozv0iD/lTOiY24ClHxAK8/qWvmz6m3/Yo+iPxd2qCsWTfasyxKkc37/GnJiV0gDbTarzoUY+NtO9R/064oObLKmgeywfTqetJI
    username: AgBU02XNjQxbpQ9bmT0jq6LZCYq7Cwd64I+ujWQso1HbrlyeAc9kaUK621uYqE7XEfgrbH6ffYgGPKoIy7vofQAK0ZkgBqKVkZuIXIf9fpZFRXeUCipjfgKKSZrUscltidRxhKLCGow87xmAnYJT17ko8EKTlSwcJckqOvD3UPpgV9RcYalKCR3b59Cu7Ls+V8+2RSuEOEiniPdY6RDrSmvzgTABMwSxiO4jCNceNnnEjpQm2dcagkAgybdlAnmaPPuAZqsSXJcQxvlJobndC3c772ruYajLbDTjd4GFg6FJzssOAVdPj5OsDSZcERmxnZRhbOmryPKN80qQzngx/96jBRz8r0RIM9CLh6HK98eNWIw1p3Asax+AxixyVRWWgIjr95giri+tXFjcDEtfwHHAXHBypwuEEoSVhppx4UFlH5Z8qqJ4zJFSfKALzSvPwkm/iaKwiyRkYn1MOrSR5gJqcQL/kfu3ARWBezT38P2EMoOlyfbZjTuKqERq30jbkIKw7M5+4i8yrSM9v1qtw643Jn5ilv210Hp7uC33TwFEA131Gb8nNllzHAOwJMS9MyXnp74ivUKOfe0MwxlPFKhBdpYKAEIM2719X8fZV/G0XnGwQ82iDUVpCTh2bLGJDmwKztcJGI5OpDDdA+XDCcS53L+2Xui77juzyXC9isA6v2j73r2yVrS0lZRCpMlcO0LJ47urAA7aNPhQUIeR1rIiNHQ=
  template:
    metadata:
      creationTimestamp: null
      labels:
        access: readonly
        app: sonarqube
        component: database
        environment: dev
        team: platform
      name: db-sonarqube-readonly-credentials
      namespace: fawkes
    type: Opaque
