---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: db-sonarqube-credentials
  namespace: fawkes
spec:
  encryptedData:
    password: AgCLm9r9fI/I7mEovh/oBRi7v37R4SXwVN22qHhMFu5hf3YJKoLYrSwKVbZK/WLnOzd+yShtzzsIkBTZgMlRTixOhJrwd3TSW/hzbck0z9s+aQU9f/BQQdvwIk7iTxjh3FPNAFkamHjAo1mvby5/wDZ3RCBFGfueUOHXqEPMPGx35fkPsUfheAa8HK/qYz8b+KsH8Bp+4DQR8Fkrd/pMDtBt/11BO8+96eLHTlCz1Hz7sH2CPR31PDlY4SVvn55h0g79SWWD028/Eg04fHeJGYE7FH9SdYwytdkB1nMTJf6V/xRFceOn1XLdXIE6Kxe7ZK9IoHCsdSA4929SaFThv3ThQ9uuOr80Ye1w1ip9zMa0rf4mJqBI+UiYiwZb00EVdJld2m2B17Rh4ZKp3CcHX6WmFFpRd7M9eMJI7RGdqs30Rlos5rmq+OGqJQiG/ZmZBjB4UCSFZdg6XIA54zxixruE+RORLEBXZzgrCMDfIgRQ6KzN4re1+4CY5VCrJJM/qkq5YKhH06hRR4vUxFR4/13O3YnkIknUm3uQ9c5UotzqDdYVGSqU7fzdmAf4os7QUpHTC2uHsoc/W9PunWXxf9SSTP77jdXQ884FDO4+Cd6WfKpQZ1NUNbomz8Arvg/xlMzZeH80xvBxSUCoKuVozkDw8RnpPoYBjuFa2jBe7Z3I04pYS0xcwd0LQrmTJwwHEhw885C9/A53LE94dO3OT9Cqf1WvUdb4N3BNF1Dm
    username: AgDRq37WSejMOFu1KddMGoN3XvObgitVVucBcFwfS45cuR4X+rA3d1PQkH9AksYIL8Khzafde+DwH8nEntbvTgQU74hauChjB6ASh7EBCtI+zbAsS8Y/Q2KVOXsi6HA9ATJ9DD0mFZZ+Xhx6EUTuWkSe6nV/DN8sC4n5pcXP+mmOBpj8gTnrxy0VjrHMHESibHorcD9I4mY+M4SEXQjUrjrivMLZOKj92oSAh6AvQtvYsKuWCZz955UOAu1Tp8jrOjcHQ5if1BVDbA2uL8p/8itLlorg73UPZqguz6oIwvAH1e/68KYuP3VlWTYtzO7NhjsnW8TR0cg1buP380By0r63paThqKTUHynm0+XGFz4/rBmvx3E+ragYaWL+i4BWemvM+NYFAb/qRXZZGU4NS/vUB7tT2vmi83bxWYGeqQ2VwYF2fyh/TD1mmCrdR+gXAXWQH06suEUsIGQ7ZqFuEhj4cOEXXUt0MltM5j61V0AXfDJ4tOXCmnm6naaJvDeQaHGTtqTNjg2lPmHXaL3CzjtXTHc/bb8ghM3BPG3ZLab+vF7GsNMBirpsShC6WwRMJwpiIH+aYUqOGROoC4CG7VUbocgQnWeNycQ8xk8ONYBYVL79Yu5vl3e2Q36Fxb6iO78TLYn99+RYZhztXIf96/CX0GsGNiFaj4sB/yfo9zohswR09/Hh+D57pxCsopWslu11rL8SnwYMuRbEYiVfOw==
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: sonarqube
        component: database
        environment: dev
        team: platform
      name: db-sonarqube-credentials
      namespace: fawkes
    type: Opaque
