---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: db-unleash-credentials
  namespace: fawkes
spec:
  encryptedData:
    database: AgAvbFjUkAq+LoX8W/MPTUepK7gk4mqDyrP4cZvQ1ghkd1FZ0rdCH7mn6gqXWG5arbgWFkr/YS8GX4MgQlXrnlzkLtlQLPeNtrOSXeJVbYCjczjZrR/RpL1znvbzyjrnKXpLXRJaymDvRIW+dJN6R/8Ozu4Hts6u/XXWIRkPStGRDv5WaGzrR7M/9wBxhM5HQ1uwkpO/KBQaSzZWpXWEzK7md5lsBsK7ndCk3RMWoNwCDaaphXNRry5YOn1KbIEWWo1DgVD+rx9S94udsGfo9PeCjEfcVBjCDAhaLDqinX576Ofyye+akZgME8ifIapaigVuv+lNgBJQhEthmgmTMo0uVF6OH1bbUgWTg0WB/TU/JwPqb9td4hkPVm+G6qNGj/23wsQ12ORw8AJ5h7IFuP8omtpmEqMT7jWwTNJVpc89aX3N8FH8B1tUBnZQH5/UDTWDrgEK2lRFCUOS4S8NVhxLy8sN/1qR+neG4OVPjqEMHKQE3XqAEfPhQjv1iTqzvCoohv1z/0Mgk3P9LoAE+5WpUdDnk2e1NeyvSjhEfZkt079vewb4J7etWKipqe+KUHur+LIvhCw92rhBmGvpYsMSq70HKH9K0PSe0J14+S8qIuc/5wsSAILBRMiF//NPAmUffqtxYyexHywOymBPyCXHLsfoLtn3wkWxXdrrFu+XQivQf3lyRxJ0mGZzIsQXfPY2W2kCmDxk
    password: AgA38qPnwapZYxSOf9HhOiR24OzJx9RKQGldz4T8kjCny8sm0wZLCKKW4hVe2nZMgekYum2tAxeQvQCumqV/e0I3MBVeUNRER8wJPgzFSt6RTPj3V6yFCvjEPwv+3wzY2JI6tFC0KplXVDDsbIMFBl6fV1ofGWr4s7JgQJ0b2Zf6yuG7sHudQeQ5r5rwWj8yYliR5FnwvuXt9k1AKlgA3hTZGIKSsV5yLQBnKeDaItO19mDRxdf+7z49OsmybMwEoC2kiSn3GFV83aJUc34x8jr3tmv4VjG4l0r9W1BNBkInf7V7B5tLPPlwRcoG9wBL3FG3l4Te/kmAzs8MEN/pGZl6x1K0KiguO9UZ3xu8+U6mE1tNdwYcVBX1xUk6xlQ4rREH4u5wOa2qtqC9XJs9rdxUMF042yeXm4aLtvEWo6QquJQP5DWs+sbb2OYTxCwS/MMU+D3g0/MtlwG9Krx3z0/PHf3CdXWNF820rPAZXPgAyhTJqv4wGIO/XEKNDAkQ5kSb57eT9NR0A+DU6Gh0JV9TbW0bZkVgr2ZKNLFJ5mqqoPUk7S8lkeALcv3H3QJXnfvfo1CFZqFbUZUsHzA3V8kWFetv9vjmgC4AEgoQnUWK9c85R+d2DctWk8QLMW6qrHri+dRHoUxXgOziOyrn44AWL2J7DbQJHXdk2t0sBB1AwDeRbWcel22XEC3hmK8cjJlvy7ca/5PzQzUfWFBSrVFw2SM/DjXsKmIatcJG
    username: AgAcxCrIXmCA3W8vCIyMWSh45t7CJjL9+BwOvqQN8PvSUfWsNnxyer7KbjZBKiikie8NzdxqXaFBOhqwa6ulha8wSGwjgt0FVqaS7AFiSTgtwH8Hq7oOFuX9U1LkqHkiC8iWze24y03xqsjfY6a9rkxfxE+ksHu9gO75hLFJzMPGqxZbm2BSmqhoTwUFAjl7AGZmg/SY6bCTcOdgiAlvHRWcIShZC+8IPjlsIfmozqqhgiWW7zobxpDftSvbvnB0/zV3shKKr1/DzEYSaNmrj7oUsXBy/YtIdlA1TH9E5PvlZRknQDUellRTemPzvqUchAo3ZHujYU4k7kLGZ3cvWq0qosmgMHhVVqTCSdTpVNO+rfDyN6r3L67umdh+lsbdEI6sFhTTKMkeXKmwxB9ya93wh3petEOs7DB4KBveK4RtQGZK1Upp9C0DlWeJVqHwQ4KFuaOiMOp6n8BdzOP44HMt3os/Ekwlp6iHQiqVcY0EmaEneZ9W1lv8NjJ5GhwN3RV8hClEtvW4cC9E66ljUrA3AD63zD7uoaLO8PuBP9TvuvIEIh81Egiykzl7qOtqpHFXfJJBfGe/CJxkjwljorH8PTJhGTQPKwu6P67vhajegvfBKTG701TVWXzb8GSQau4Ga1RZachQCLkKAMdbisiINyBrtjwddCBMgyrwXfy/hfk+e7WAEIzh+FrgCa/WDnb8lzI8B2wer8vHsSw=
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: unleash
        component: database
        environment: dev
        team: platform
      name: db-unleash-credentials
      namespace: fawkes
    type: Opaque
