---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: db-vsm-credentials
  namespace: fawkes
spec:
  encryptedData:
    password: AgAHW7jxjaxJmPqCY5+iyD3T9KXgsQXYKPe+TQlf2t1IjXmXKqduWVxchdv0oufI8FeJjInLBXtRkpd1/mvZw8Xr9H/jka+V39BM69JgsIC7Oivv08BVWAVwDauUmWUbX7kfk/SypCx1h1y9ct0/vQ64Uj+YnsY2SczaBLnfE6hDVOQXzAWK6V+wRU58t+eJN8EexC07/B0KIk4iclCCqCWLr/UED9Izfa0/ZYO8Vnrt4AwWZZwucQOoPne4iEFYpoyY0MifpeKVBlNIoyttCye80kSSVvNuO6EiCqiWMp3e8LJogtIUMeFpIt3qMf6JNWFfQdrxRkzUMf0yu6wJyxz2JZyEuIlpQis+4bkm9WQkLLnEzng+BvoJ37UHpDnvqPPll3g5ku/viJ/34Ic0ptgPQg0N6hYt2EcmVbL4zNjGGiJQmBwgPwgfo2KaLHIx6FZbyg9NmbD2hGIdneGgOL2o0i8zxbYJ6B6q7XuQ7xOa8OOD8UaTBTPxrOuJrBO8eDCyIbf78bKwRm/iV0cgASgUGTJONdhHRFOFB7deXe/TW6rmBb8ieCbI/YilpzVDiT0TpiLIYSInqbTFuUUwgMT+EwTTAn0RPSuGFrrXHt1GOFW145btQL5BsnMzoI6s95MGLLRVrGpIRjtZZZz3CfJV45nNjNRfCRKpccLKGRdFPLP+910mMkrdtPkxbw1obIFpTu+TvbHTyg8n6Hg0xqN6gNqjv2c=
    pgpass: AgC8QG9bYx2RbOO00sCfJqgA7g5nZgRiKWcK3u6mFUA0k7EEZoI26YQ1RUFHGRTKlFtRdyfUFMmkg7YoTcfoFgmuyiucEYgurbk6Yf9fjbNmCTHyAiS9rJTwEkedRH1Pgfj+TCod+5+gJ0+rWJM/VaiaehFnJQcuUcbu3yBhAM+WniqVj0r8WViWCqDesRx/qnO5t2mdhv0LCuObug+ZoH8EriMu2tcDYraARewlaH0V6zC6omd4+OPpra6WlZc3tbMcLmunWjVDAtggv68cVPbk1CZYCS7i4pL22F1sEarsvS97MEcMPJz9ZFUEsj3lLpB8/+waRm9E6OukEUU8V+Sb597tpnR8vHrxyfiimop1YrpNIXBNb+7Dx3ZVWd1KX8VR14jqrh+EHp1xr8jCR168nesZgnfpPcYE0btB7+mZabydHD2ALem8QNB8YVETJ9fC1ltenwJjhZ9SR+WAEy//i3A5M8aW/xkeaWpK2UjdF/MkLvnB6+MxvgXCZKOUh4AvsW7tcUA7cUDw0GFqi7e/oOX+mnumvCmgsJoragxu4sL6VSqmXyP9tbCaUuM/M4A4bWVvnghf4pYgIVT+aW99/kaMIindQtQAIEkPXwmB9QGxgRkImpaC7vD2/oTs3SKFNC0+AeLVjkm0Fkb2yJyA/9jxgyDfILLi4jXMpHnoqFXqTjmdazuBtMCG8LgvnRUMyKoImk8bF4S16mOVXTWbFvaqGl30ud9Fz2VNy/1dIBauVglFMUTn+VCwHCQx1CNDa/crZfj9bBPrGGMVXoC58Z9k
    username: AgCPNWrmVRRkewYDkiV+wCjaRbSvnSK2n7sd/Jv1UiRjOcDdKwn8edqB8fq4BPgtmCbFvfQ7brP6oSbhJrw8+E+/H63/dwMqf8jHzmq600AOHVONHF/UXN034FueYGylrKl3XMmiCRiNOJmvLvDTU8QLi0f61qvGwdLC0uJLstaUpFd12dXyOTPtex8FHwn1nJzIT4SpywKxzIYAOjTuR6br6VxDMgm0Milfsfil/Yn7pjCWb4JMdC/OMKmdIq5SqAa4Tlw5jm7Rj/lowH5q8kUXdlVz4UgsToGONCK9dsmGZ1O80UAGUrLEwelK4Q0JDkD8UB9hhZVWwM/gHIL7tMG9ttBbmLqQuNlzzlecxrmkyVTZa+QhY3hvu4RqsxgS+p2OFW99g/WM6syHfW+DZ97kLP3izjZb0jiE3JT6LDjQb6wdk+Me4FVXMiqWyUJjitgEIpiwlPpD4e+cLTGmEwYa157+SxgsF0bk5DdytppKt9smBD+mPb++HMCxQgormXnU1M2PPLxX72MaMBqUZBQ67pGm7Upb2fJTEQT92C7tbqLWK+Hxiz2E3tCndVJEH1lhyx5sqZue4SS1BbaY2n22ZMxJn8vPfQVk4UffbBQcG+iBTirLlHoq8jdLs9wqDt/giDZhvxI0VIrMdfKnnmSP9pcFggPvaNS9IUcmYpYwyvcjc2mxTjEpLBXN0v7jDSRygsJTvRL1Ow==
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: vsm-service
        component: database
        environment: dev
      name: db-vsm-credentials
      namespace: fawkes
    type: Opaque
