---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: penpot-db-credentials
  namespace: fawkes
spec:
  encryptedData:
    password: AgBL3IZDli3J4zEEiVzbJDtb61tOCwd8f9UCgt92NIFxT+F1PNUdy64/tDaDwfTsylqd4Tp9D/GbglWRKIcuaes19WE+EPHedOGnZ5uGkvifeKNfEf1cqjDV2uBPoeZ4eBFKFB2rJYNLOdqkwoNBMfEXuew7HA3AEEuRAcCB6igGYtq8/EW6eDC83nnRbn/X7Mj0Q94o0YEcMqZnhuPssZUUY3LqbVOtY36gqsWcP9Cr2zv0vsrF5XsX1OPbcvbw4PRvLkDPlSA2toSFq1fOmtw3PZKj4pOTErC9uWdPN9eqJS4RrgCCfQL99VgN8hvCmQoatrzfX872j44kuQuvuQY0mE+HGeAiS+jbsDBm/4LRl5DjaAZhlZn4zzFoWZ/pNG/thb25ksB0B9Qazrc56iPbgT378RWwV4hvcAz4YlFgnL4i2j4nftxVI+I4TYMuJgh7pCICgDgMMvP2fauPBbdv9CyEaag7Pq5mwJirQq1wO6R/OXDgr9/ZM73O3R+JsJjsNMETWWbv8Sru9LYHqBaNE6tyUcePW4MfemRJeYWZosneNEGS3PmlXeduHcwt3f/VyMgd5Jnks8lyMWlolcUlIkErnya4sS/xDx1FitSQjgHww3eSZeEudrSPF/VzkDoOLxrVRsxY9h49PhctSKm5NRSF17cSiy1C3x67tDcmpZJU94/Tf2ATPqYNFs9rvN2gf840BTVrlDGKbeWTlkz8/PfXcFjSN3zLi5Jx
    username: AgA7y/yjRVx3cb/G0Gt3N5L+9/SYtkrUwNBkEsUnOqLfgnS6keu4z9yXV5BwVVTAl1/e6B96aQHKY3bT1zTN+5FaP8x9RCcKphbWGIbJ4RXukHc6YGUoPBN0F2sT0nPStBnXAQJZEpHhCdY8ZTuX8QJHrcalvwtBMo/7tWLoA0azuQPFHWXzS/Ku3TMKrLNDqWaw4rbsEKuNQHavUqrowkF07EzB4LgMBMIRWD1nd9qGAKbQv0P9zMNw4FywrW4tSX3O2JBDnBf98CXCq/pyO5E3jOP1fIkGkS2u7kqzPoWX0V9EvEasLCe/shbJ3GTxbcbiAyEgoZy00eaHHjI8xH+nE6E4Y5zem7XCfQ/wDipQi/6UVd4Zl9CD/Llplf2BPPqDKHgp+949GIeTLVeaOAEuMDrC32NW+9f88YaGTeTuOKtGw6ITEe5JzMH7jtf+FOVzuyZF5sRl4zrRg689BGpcEEWXV4YaTl5WJdS7h3BbtMfTxLbfoykaHc/rVCqnxwDwypCbeQSufgDuSf1LI2/Hl0g4TyKKuwcnZ1iIZlr2D22G5IOSEyZ4c2z3GL2FWYFpPQwJ2nq/uxJBJSaF0JMRp331EHn29mkjnCu/MCXH7jKe+WXqsVjvSZ275XndOvlKFTmp5Kdn5DilO71laH7V7oberNBoFmoAA9nRP/N2HRng7xNsi+pVj9Hn1Z4g8eyGWboZAFY=
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: penpot
        component: database
        environment: dev
        team: platform
      name: penpot-db-credentials
      namespace: fawkes
    type: Opaque
