---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: db-devex-credentials
  namespace: fawkes
spec:
  encryptedData:
    password: AgCt2hWjoR0ZFgrqZOXtyaqGronJAQn/i6Bi5E5VjNKsVxLSBRwgd62kzr+xwZntncTrg1kfOircrsGJCY49YDh/rDcTiDDwrTBcV2IQq36YCfkIjK2U1U8PFyvpQkL3X0gJOdVB6qzQffxkwLS8HnliFMzHqJE8klXefm75eQbECO1EicvHwULsWQl4xv3dRMqapg5xXEHG2M3G6bOLrjuk6M/wZ7KOKHthnCN73Yko6hV8/tJDwbcBaouS3exF8lw11hBgKKSeMR0C/uBTR2g39oON7YqH3li0sJQc5OLEIWPc24NL3EsBt1yfwxjpJ9bQBVdlGXP+NXRpVP7kUiIb4N6mbN5jAG5o1unnzBsmNDIvPbZ8J2hQmjD5EiRAjGPi0FjZvZfH8l0OqmMv+kAUTQh434SMi/pCyN/dCdaCf/TmmZR1HUn50qV4hRkPKc+6Kej0OiSngKOCJfIlSoPUVLnIlkJLRydg4dIyxuR0I81N7sGaTqOVrCc2rNL6NLHs42PD340WSGZ/WYK/Wo7WavAcWZOI9LS3Wi4ybL3RiY4X3ntHR/5WthYpTNkI8VvJhSv7J7Z8JVn8uP0bbpk8V7oRSsf1nph9yqVcgqfh8i+kmGaqN5WlsVNwL6MysIQu4Nq1jqcr0EFI7Z7VwBleSD83fnlx2V1ajmvollxDHobwC041R6DgSmPha9QeY6lALx4B+Jr+jXpmscNEY9N+m/hzsUSG4V2PHFuX
    username: AgCRh/tBzDo0pIPQHQzGz8kQ4K2kZ9+7N7/xZ8kticIqLRqvk+6lwNrAMjbt0imFvrOLZUxzgJBaYABMAYev54k2p+S6kXos48YGT19e4Cr7iilZ7bABnuzn7WH9WPgB98gFy7SuPlEqu330sAN4chdB3ia1iy0arPS6O8GaM8MjrwTRh+4SzjML+zeyCuP4yWMOsIaFto2ihQIFGjH8RO0lXtLd9fW15w46fKkuu6ZoByf03c6lO2ZZm4RvQr3KUuHjYlw3Tpl95JxSdjWmu6Grs7WjXgXU9L89yvB87ySq/DFpveS8ES4yHjwEUlY/bv38Yo1nzeglNdRZBdNkTQB0Ur0HMoZJDgC/hj7aFaUlWAOvYIbePgDRk3srE2txmK4cg24niQq0diIqYZXEp86zbwTTG6IPB5oDO5Ozxo9mO3zSgUuVOkJ71ZUnc2upV0+0GDTpJd5zrjnXH+mfw4ZE9g3d1SB2lxsyUBBGchqop4A6b9Ro0e6W88quzh/l4b2Pfr25xTtBah+QRf1EkN2cPF5JX0sy76JU93iDxJbCQHtdm5VTzWMrtFQHqVi8/9kUj14k+WsTryIawE0+zE4s5OXM3yG9wf98sYpV9YEKEH7wsa+jQ8K9GkalwNNwoeDpC0e92iaFSPo0LKo5cLyR42GTbo+1Uox21FH0ba4R0Wwho2xHMgRMOkRtb3TE/WrCZjS7rA==
  template:
    metadata:
      creationTimestamp: null
      name: db-devex-credentials
      namespace: fawkes
    type: Opaque
