apiVersion: v1
kind: Service
metadata:
  name: tracer-bullet
  namespace: fawkes
  labels:
    app: tracer-bullet
    app.kubernetes.io/name: tracer-bullet
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: fawkes
    app.kubernetes.io/managed-by: argocd
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: tracer-bullet
