apiVersion: v1
kind: ServiceAccount
metadata:
  name: tracer-bullet
  namespace: fawkes
  labels:
    app: tracer-bullet
    app.kubernetes.io/name: tracer-bullet
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: fawkes
    app.kubernetes.io/managed-by: argocd
