---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: harbor-admin-credentials
  namespace: fawkes
spec:
  encryptedData:
    admin-password: AgA6X4dKyVgvtRxffKh9Il9Cft1lSOXu4qxiyNNYyhUvCiDHiHPU8EJslr3e8qbUC159c5Ii5fNG76n1iDyyO8D4Be9ZfkxuWYc35XGH2Lz+nnUvh/oi3X0YkwtSTJnVAF6RLmRV6WUzWp4AB2NS1pOZKF5znLppcGqiSKqIOVo9cBgg2JDpy26aPZ54Pyq/X+k9mYUbdUNaJUz42dTsj/a8vJo+sWDr9zfdCd2FXPrSRJEVEnyz9sgu4/QtbPY7bZiZ9kdhiFp/PtCyDMztn2nVnuLkmF5JIT1HNsxH++4dyOyM/muYAEjFkF94T/AZEGYHGpRrOPe0VHxG90BYRRH5NC0OCw6DdksxwqfP3lBLNJQtatw0ax580DRYU3GWHT7WfDD0Hysj1+3M1JwoRYdz1xKdSZONHMNBmMqAXWwdcBrLH3Te9vLdT4crqs3iCDy1uYTbyiVZ0trMKE4mVCQXkR88sMPzWZKnRpSowEAKsFfggxi0nYdvuu0g+Ki1deRYHT7pvF+i0WElc7XpjbrARdX7+8YsA9H/IgJjIIMkg+0r3NkW79gHwOOHf5itncibMYqdD+dU3O6B5j8gSUn8F/3dNmw7NgGO4wx7TBHvNIUOSR4/jpik+D3gW0JKPH7rRTYyVBUkNe5Yz7ljXThyD64hZ19XJXB7fPKsaSTICvL+YP3lCX6+eQhixB3XSZengkdaTP3VOzi8UQ==
    secret-key: AgApYRc3U5ekCq3haTblKxw2h9nZfF/jbnB7d3iQJbdqMK6UC8q4nCU5M53wsJ4cT2DEVXlkgvtn5KNgf1vHurAR9zGm5GMp7oGgjI/YC8KnohnqWrn4iRsMvcuAsyXmOwT+O8v2tVhC18jFtFEtb2LiOjNZ0tUgf0wbQ8UIrSTS/Idycj5DaG1J1kLMqgDec56vRUtXiI3bxNgWZmqDN1Z8icNZhdVW00o8JvZ/Knox93XsO+mwPSkyiqMAd01sXRUCi81h4nRNOssCrH/uyBsTvJ1B+Pi8HIuV1H6G6NkINZ/a5UoqZCMhT1iMl2vXdPofLdir5c8dPlsZvawY7cg8n+FI+dXs3MA7QvKTdlLlw4Lbf/5MrhcLBoBhO/fFK7meYBELPQ2DB/idLdrcJ+m+61vED+kwfM0k6NVGQGmk/kotUWDZwlj4ycdBrxd870qBKef6v6kZaHsxT1X8eJ03eQ+uSYR9GD0P5ST8yreCCtIpz/oGZOXCuHA/vQJ8QmlkWPRk5XNFcSNf+qy/Z8je/0VbQrGnZfhw88AQud8R4pKUasFfTFGKlTQpuHHo9Iep5w7kdXZFdxwwIkDKHrIAbF1+uv/BeIJ443yXait29bp+R+ULXgEdr5PM37CdzkKIG/lyPoJob1hnUBZgpTWWWhzE7H4J7ZjXWi8pEVWwUkDZs7sJ4dB1SsGcndtihkqg/rHGQD8CNzCY7IsJeO3IaNRCyG5b6wu5hPReNP9vMsukjjj5
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: harbor
        component: core
        environment: dev
        team: platform
      name: harbor-admin-credentials
      namespace: fawkes
    type: Opaque
