apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: fawkes-services
  title: Fawkes Services
  description: All microservices in the Fawkes platform
  annotations:
    backstage.io/managed-by-location: url:https://github.com/paruff/fawkes/blob/main/services/location.yaml
spec:
  type: url
  targets:
    - https://github.com/paruff/fawkes/blob/main/services/analytics-dashboard/catalog-info.yaml
    - https://github.com/paruff/fawkes/blob/main/services/anomaly-detection/catalog-info.yaml
    - https://github.com/paruff/fawkes/blob/main/services/cloud-provider/catalog-info.yaml
    - https://github.com/paruff/fawkes/blob/main/services/data-api/catalog-info.yaml
    - https://github.com/paruff/fawkes/blob/main/services/data-quality/catalog-info.yaml
    - https://github.com/paruff/fawkes/blob/main/services/devex-survey-automation/catalog-info.yaml
    - https://github.com/paruff/fawkes/blob/main/services/discovery-metrics/catalog-info.yaml
    - https://github.com/paruff/fawkes/blob/main/services/experimentation/catalog-info.yaml
    - https://github.com/paruff/fawkes/blob/main/services/feedback/catalog-info.yaml
    - https://github.com/paruff/fawkes/blob/main/services/feedback-bot/catalog-info.yaml
    - https://github.com/paruff/fawkes/blob/main/services/feedback-cli/catalog-info.yaml
    - https://github.com/paruff/fawkes/blob/main/services/friction-bot/catalog-info.yaml
    - https://github.com/paruff/fawkes/blob/main/services/friction-cli/catalog-info.yaml
    - https://github.com/paruff/fawkes/blob/main/services/insights/catalog-info.yaml
    - https://github.com/paruff/fawkes/blob/main/services/mcp-k8s-server/catalog-info.yaml
    - https://github.com/paruff/fawkes/blob/main/services/nps/catalog-info.yaml
    - https://github.com/paruff/fawkes/blob/main/services/rag/catalog-info.yaml
    - https://github.com/paruff/fawkes/blob/main/services/smart-alerting/catalog-info.yaml
    - https://github.com/paruff/fawkes/blob/main/services/space-metrics/catalog-info.yaml
    - https://github.com/paruff/fawkes/blob/main/services/tracer-bullet/catalog-info.yaml
    - https://github.com/paruff/fawkes/blob/main/services/vsm/catalog-info.yaml
    - https://github.com/paruff/fawkes/blob/main/services/ai-code-review/catalog-info.yaml
