apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - sealed-secrets-application.yaml
  - sealed-secrets-key.yaml
  - sealed-secrets-key-template.yaml

commonLabels:
  app.kubernetes.io/part-of: fawkes
  app.kubernetes.io/managed-by: kustomize
