apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: hello-fawkes
  description: White Belt Module 1 Lab service — hello-fawkes golden path example
  annotations:
    github.com/project-slug: paruff/fawkes
    backstage.io/kubernetes-id: hello-fawkes
    backstage.io/kubernetes-namespace: dojo-lab-01
  tags:
    - dojo
    - white-belt
    - lab
spec:
  type: service
  lifecycle: experimental
  owner: dojo-student
