---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: jenkins-admin-credentials
  namespace: fawkes
spec:
  encryptedData:
    password: AgBIb0zpQ/qVT96ywDHxjqqYHjVXxbGdL99vLPTnNhvdiLOBTfS7L42dCwNp5cYvTWDjQV8zyigo5IpzBIXWZYlGGptsmFG1nvUSCfp0jXHXJ65hx+kvON7q+fvTYMJSuKtLSeFrpz3XFic3fDK9hvAwpa8U7Vg0aDRX3n11O9DrbN2GFPPIrej+O9MyHp8LJPWrxft8iSnx0mOi5hsqAuS95c9WXk0knSOORKtLcKKYh7/UtRWftXekoFNugo1IdrQkjIsjny1PPDNwa4ruTmuNmOLbWpZsk5XndBmeXMJN1kAS+OcmJ9++QTGb3VBtcFwiKbG/p4onsDBHtuuBKB1nVHmBsl+J6L2T5KwaWeJWb5QKkeKjamYszWJAUzca5/20HLEi78yRubGKLm+oOi7TFmEjSKlASbhPQaaFtUN6BFV6wCY86LP6chx2lTmzVVFSKg5bNj2dNgygWqb3/4KCBTLrBcTok82+HZhXgHcVez9ZYFjTw2Ta5CBFP8HUOdA9EqCV4FC3MsIjHY6UVWjZ1VSyraaMdeqSCm5jrbdkMXj5Eq699An3hoOowlfJh/dqY37OLjSrZBdZ0W3rMxQLaCG4KrFrGl6xOcLoV3NlB6201+QnpP1S9d6pHd1IHWprWB16oRCk8zOeMYKApAg1Z7X45itXKisZeL69NOUcwvBBv6rfOyXK0bcqEFxEQCjEp97yasfwSKHiXd2eQewOEoJZVpnQz+VwlxqPj32Xeg==
    username: AgAVWJJv4T4AVO14598NFkZ81d6Oup8y1is9yjP2a+JtXx5iM/4eyKuGgO9BDvHXgvDj8ch5HT0MoD+UdJJ8Ttzc4/tF2vC7CtJbt9x0qKmdcWvyZUaBYSux0VYlo50isqNgND/kwMAi6Y6OQkrD/oK1zkQNOgK2FNPOhW6M9YJw+Hg9ZmTAbAVgRVGNP0p1BgV/M76NoUz9LPF01XVay6V/YBRmdd4VURIbMwHc3i5tyuAUAbVnDqYA4BVRPwjYEKk2iGnOltMhdvN+xUaLVFAPiSPbd2XrcC7B86h7iIYF+C0vql4/K3tuLVio1gCB5glAbrXzMxqRoV0QH5QlcQ4/KN/b+U9Bubb2iqd8miUq+YjuTccGCySfcQnBmKLiFXTxVGGSHqJEBQBbkqkw3Me9SjNYefTkB/sqe1m72xPnlKWSrp7l1G5R52XZu8PUCGSuCrzVT2U0noC4x0ASCSwuneJC6RoHb51dhg3wQwdH6M833N46DQJAl1K5dpuTx5knJ73gcotd5gRBLOqB4UzqCn6LUiARoiMhnrpM5xl/N/dcYS7La8ZovlC1IiFS6HouR4kw8Q3W5/1wFco8wt9RXGEjLScKnMrOjqJzg4TZbIrrfDBWBaRLh8HqY/pc97yRlFCtDjoIHTxrNpYa/4I3r5bm3YzMwxG0QK6B09wBH6GuJP5oQus7dldVY1NL0L3rh7juow==
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: jenkins
        component: ci-cd
        environment: dev
        team: platform
      name: jenkins-admin-credentials
      namespace: fawkes
    type: Opaque
