title: Deployment Configuration
properties:
  environment:
    title: Initial Environment
    type: string
    description: Where should this service be deployed initially?
    default: dev
    enum:
      - dev
      - staging
      - production

  port:
    title: Service Port
    type: number
    description: Port your service listens on
    default: 8000
