title: Repository Configuration
required:
  - repoUrl
properties:
  repoUrl:
    title: Repository Location
    type: string
    ui:field: RepoUrlPicker
    ui:options:
      allowedHosts:
        - github.com
