---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: db-feedback-credentials
  namespace: fawkes
spec:
  encryptedData:
    password: AgCJDh0Mdx9pCoC3071j8kvPE2kyDTwC2bs8jQtvwDmqF3diMhrPudDFdteKgRnaE/EXK5C5grmEQXYIPyPPjbCPzWMTReCM53lSIhjaxwpqQ7On2JqBQmyvJaHeOB9JBVWV4NIogi/1Kv6KFeY2fWCFzjan/t1NRdmL1NxmT9dcS0EgZlSC5QQCiEmJiRzzgSSIWbYHJl+1u+KozjCeJufBPsFxt3GlQhMtGvHad9MFC5On080HCA5PZXn+eX8Qt25C1RAR06Px9f2oJ9BelVYOrxwehZaUxo1+JOQ1YSGd16cRaGBP9+xVZei3L/A6pc72b/dDDafRFusyNueVCKE9TPb3SKtN/a/iG0PKJYHgd7AtEOGzbLhT+Zgmc5uWOhOf9SJxQJcIAAKKbWnP+SEgiwL8cmYbkU/6xRKwJjXSuR63fryThnfi0xwZDjkg/zj9uOfyrEHYa9tCcE6ozrhXl5DFCXM0UTML+Fe0dWHJREQP6SOoJYjwrseIFC9w2lBfylPJdsmbj5Me4hFkqcc3KLbBz8pTm83o4qk7aBAx7t9WhIuXC/nKxqgE4oFTTFufcDFT/4cXoAOtheIryiUivU3JL7qU56N9xTrCE5EJA7xki8Xq0mj2v0ixbyN71PP2IOx1R6rvhjC2zNiG/4Z0CNP1kkZD/KUbaIS/w30rMIRdvEXaxjbuM43iB2RELQrVXV1ddiQBXpVnPFr/JUffUntLENqSYlJu4KfG5VsBOwI=
    username: AgAGceePnRSwlJ5NyvPvE9Lh+vT7Ycjddp0RoRVVz7CDqLlgyJl0cBo1Ypenx6ZhyUDCSVWLkiaWhMPLFI/Ye6iNQoABYHz8mP2xERhTZ/WX9YEHVurbOdXooleFlzaPHpUy9BcR67uLj1y/DOHDaeSPO7th0Yi4ppRNWmaW7NgncOb7AJ9WxO/wWSlPPNlnYf+FmN1wKlia2m+oIcOLwGIBCY+IueyI49VzCY0RhhoCJGz9IB8/QdaQLTEIg+CgXNZqudLA2X+i9gk1LzGdEASFu84l+j8M4RyukBKhvyIyGBgvW45G3eQimVM0hMotjjlJlHCVKI19m1Cmjr6G1csqYZyEC5ldFaran6wLtENehj2LpAu+aRQvt8RU3DR6VW2DLNXMmvqy8kriOBU5t56qcUzrHQPzAthYgCxn0SsINbdcERTTh2DvoHuCzf9dD477ysznz+YJztsGQ7WNG2ZWDapxz0uGdSWw5d12BfmuXTV63qmVt4JB2gQzgXEPXFe1Bq4CjwcTQyXKrKAVDBENno23K5+AGys1cbftonucPUEy+y/xLOhFMEo4RN4KAEtRCVBg9Bee+sOw/cOFVZ5VSiy6++XHQFGguqw95bJX7hAwGmXZSIrxn++GgFSpCJnkhh0eQ66xoIrRpOa3avjrV/t4+PjTW/VKX4+VR/9Pm/HA5HB0aL0kLvPWXLnAD/8Jx6h/eTN0gA==
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: feedback-service
        component: feedback
        environment: dev
        team: platform
      name: db-feedback-credentials
      namespace: fawkes
    type: Opaque
