---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: backstage-jenkins-credentials
  namespace: fawkes
spec:
  encryptedData:
    api-key: AgBXkyIUs2wV1Krxqy8zPd4Ix+s5tjd4HCRTUJSrLzVWMidrkYyHluIlntLVR2DYBCYJwBnpoJeJ+SC83bhc10nNk2iwkPy057WTMw6hf2svf7L8wV0SJOSVEmWXYSo6stUqLXIFAymxzGJvUBGeVbmK/g5ksa9RG6icoN8SK+wHr4qCp4innXYjWEALIu20TAZz4O75nLRABLKNkP46BQCfY1/unHRbEmmGIGzm96NAiAYlUiYRZGeEGZgWHHqKWzykcrOlX3u1uhQqj1eGb4unfzwB9oRbtQHYsIRNnRIAZRQ20+lGvuWyxVohw0tMsqW+pwmkOMV7EGJcybbUQ+uMWcAcAKxyFLh7FlT+JQJnzlfLfe/L/LqOPue3SzAgwg8qsArvDPh9xTl+fT5Oyi9aloeuthbHgeRxiv3DAcpOXVT01kZZoKB3uWANDR2L8ZHC8UwVCwGFDa1LiXUhekC9b3Qi7onMnHVoNKNN/e+gL28MuKrYBKCLknKXni6GVvAeYPp6yOgvuiGa67LGCNDaFE6IR5SrdSg4IPTz/b9vJNPJyMKeMlKl4AlBPwCT224/cPtAUB2b8PAv6+2ZSA8pfQjHdL0O0j4B6o+Z815eaSkenH2wiEoOqGh9gD93HtOzGxRTlPf/0oBdvqT3gQRnJGq0UH4SwGgHZHesmrJCAn+1KbR9GHJdylFi7jfmkFZQN/kUzpBN2Qo1S6f5KvipvjMXzskwC7PBdis=
    username: AgAMImPCqDg4Un8I2bpthReYzrBl306dd5WGmKOMDZkzD2/f/NJChXzZswh9exFCP64VzcFy6MyKawDanaxf57V1Pkd5CowFNwnKzYmilnvrUNWZjXj5XL6Zy64Mfaw4yclqHrxWIi9VOMRRdbWOCgC0gSDrX0+SXf8Ba4wqHlkNbn9DDJ4D7Frd85YpolhdCol50HnFRM+3syLOAjchALzVW3QxXZw3eQ34SxIKPLwbmt4K7EOJ93pDCE8c2GOuDqaddNFwkSYyTSB1uXt0S4Csie7mXuridgxjAAhixSEyevxrF+b67kMwDSgdkZd8uds0cw7T4pIP6vd1Uj7yMbk6hw8va3iAaWx7NfW6uuZ4A8WgbyCj5nvLw4SQ7hzhhJA60fR6GlmYrDL2KIDCJ6Jr8yyPS9kjqpVepACn7BQgXFRSF48J2msVGQFBePSMDGCEsoyDczJu85nVH12IzPbts2QgF7LGiW8bqpHLkL5S0/My41dOxxmUOFbUqVLpMZ4w5FZSKSTnOzuya2uK3+GTLtd3SEtNzNUih59yqSWSP5QK/Ym6qWoSgAogkIzxL8TxfaxeH01H3fJLjsPihYbihy+8P6XRJC824DYERlkwjC5ZPFNu7am1WGWlpKF6AztnUomiLzZso5iFrupoQ/9KNsPLr3R8CfbmCqVdYULShY5TNw1gvSNV3v5V5LrUN/nvuJ7cUw==
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: backstage
        component: developer-portal
        environment: dev
        team: platform
      name: backstage-jenkins-credentials
      namespace: fawkes
    type: Opaque
