---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: backstage-argocd-credentials
  namespace: fawkes
spec:
  encryptedData:
    password: AgCBfzeAymK/9uOJ6kQt4zDrpvvWBjrNuBaCpR381aMtdMdUDP4+shA47lvQ4MOaU8oGU7/ewpzGo97r4QXvRq9wA6IZDtaBuzz+2VcaWCIw+64sTSfUGYNeOmcpHkbvVERxTyYX6wS0CTF2fm2wxojSw18ltgrHuXASyI8HqPYNI6B+4d4VoEwcEMyOwGY3H5ZpJr+hsGIf+V4aqLSt2g70O90kOM3vkP3PTV5qnSKc+wOK8ihWaWJjcQSPoCSZa1+KUxcIcOYzyTpoB2cC/Ef5QF2XHlJSroHSTddTkhLwKF0uJyf1i8zDGG1ak3KWZRTspQkcfzunSz6PKKdV6N//lhYNDm2beKCpKQ+ftWzvVDPfAT3U5DxHgQHEjuBn0B5DJ7wGp971oHjcRxgyCFIQlN2/mjv/KhASf2uyK2vX78H6pnGMbwEpOk89YqtHTApJypcOTL5tmwFzGaljxqLj1wq0vrWnfWD6e9IlWb6Iqpt9zCLQSrUu7xGJcWjdUd+G+0zCd38X2erhwxMIBEkyfoDQdg3d9XhDNJsaqgpHtih+80QAUivoU/FjdggyhWiF7u5NFR16vu59oqZIakLl7xzEY3tfsYSPexxiN3JnXuy/b3JV7RUPXhrlYb/DTikyrXAsJhtJ9KHrW9H6b34kgUlxCVx1RqQ64Ll5bORnZkxGYVfK6zzFsQym2NvD3+1d3ITsKMTEH9QAVP0NnbsliQa+75dajQ7MFCFqk9Hs
    token: AgA9bPow7rTpRvfJ33ebf4tf6RBY434tIdTs2s8URIqeg/gDjaxPRq5FYGk5XYjpc4/gVvAthwnmU/4XUb7scepJv+jPwwS8waEDgTjqI/aAWPRevnRufXwQmfnSrTjJ1DMt+Xo0pnDM7sTCKWjT0RTiKekWC5SQk89H1zOxTsKjNLXZwnNnmJJD/IGin+QChbjV2HNCgLxSCh48z79CMq3mPpi/ZULrhbVuaycyU6Soa7hemX8ot/hD+AgjNvsoOkyRQ8MBxKIhghSSVSRZSSTfTg9xzULn19RQjU/Nx5/qYVZIkQFwJqAVc01oZzilRYRU6SfkOpetLRswdHCzvZQRFEOvxE2C3ITyvEi1rg7fTBHPu87ru5RpiBalMx1XN6bGZeUOvGySGeISuHHiw3nq6y6E8GsEhSKbkmgREaTNQ1JQ47VGiAQUDQ3K6SLbYbZn6M1HTnOW+/BFJJtTQE1JBrEdxiQmG6clkrVG6tWuWA4LeHDjwj8BY3lQl2U3QLFUCCKSXFjR16mL+eFnEfLXgeyBMkweFmgVr8ADlC0Xzjq5Eguon1vJSB2TJ9e+2J+/kcaPtn+ofA3RZR9OfR/cCXrVJNtyEuWIhFgl5zEKVOJid94yFG+0XCXtqXZ5/FSeVY+77gixbK9JGIMN5b4T0hxUiNuKODjjxVMqPzzPwErD0F61RQr5qpyznqE8sjDqb+AsSFdeWniw6NxMNfnOYMEpXEPeAo3jIQ==
    username: AgC04C1Uy1ZhI3btBB4Fe+E+TxCTIR0SECTtWNfLjpMOXPgn0yYf0T3yH2MlzuSwtffEtpZuMGWtZs5p/SYXW9VfP7Z7cBO1ACPd0aNWqm98WfIDKCNZ9ezXjXNWGMuzF9Vzx2TkwSsjkp7/n8PEo0rVdj80RZFD6TGXKYDMYpaPsPiRkMicu/mE7oNAD6iWveaxEZXs2XTIIW+ipweAs1uGOEA8hoQQrECfB7vvn60prVgfC4cc1ImziEojMNqeagJ16P6URZ/0jNAgbnH1j/9kPhTlUywq5tItjqTcl/9lbgLXAjxw3akwYoekfXWgi0HSTjAg6r8vpR5rMjgQmQRQ0IryqQYgaV5BnjxPVS0/w2cEsFQ8bZafBkYx2uq56/Tziwu/LUjTgcdTN29a3xOKXOjtsH+9r6SEYTIQeVZFDHXLIvzgAwG9/aITwu3E2CvdHDKRxRpuhBBLeKk1C/j13rCw7g2eJB3gwXbWolUvIvRsaPBTkF+92vnrkjrRDyjKvpvg5x5Ceen1AvH5D2NXVqYS+XQAPerI6V1zd3J9GDVVbQzbS3bW9R0V0PtnovD7vJ8YymW7i8gRJB/egNzVCzBBH29BWK9jPfCJXm/716RgPik3vVrBDMv7POUi8Vobx7puDE7vKdQIGnkE09PVRrnk2nQKj9qYJXsguOIxQIMvfV1mt3/cC8rQBDt+FOkTvTruog==
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: backstage
        component: developer-portal
        environment: dev
        team: platform
      name: backstage-argocd-credentials
      namespace: fawkes
    type: Opaque
